### ISSUE TITLE
[bug #28] Fix build with llvm 11.0.0

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avarice#28]
leres <None>
2020-08-29 20:13:44.043000

Here's a patch that unbreaks building on FreeBSD 13.0-CURRENT (r364847) with llvm 11.0.0:
~~~
--- devdescr.o ---
devdescr.cc:2251:2: error: type 'gdb_io_reg_def_type []' cannot be narrowed to 'bool' in initializer list [-Wc++11-narrowing]
        atmega32m1_io_registers,
        ^~~~~~~~~~~~~~~~~~~~~~~
devdescr.cc:2251:2: note: insert an explicit cast to silence this issue
        atmega32m1_io_registers,
        ^~~~~~~~~~~~~~~~~~~~~~~
        static_cast<bool>(     )
devdescr.cc:2375:2: error: type 'gdb_io_reg_def_type []' cannot be narrowed to 'bool' in initializer list [-Wc++11-narrowing]
        atmega32c1_io_registers,
        ^~~~~~~~~~~~~~~~~~~~~~~
devdescr.cc:2375:2: note: insert an explicit cast to silence this issue
        atmega32c1_io_registers,
        ^~~~~~~~~~~~~~~~~~~~~~~
        static_cast<bool>(     )
devdescr.cc:2375:2: warning: address of array 'atmega32c1_io_registers' will always evaluate to 'true' [-Wpointer-bool-conversion]
        atmega32c1_io_registers,
        ^~~~~~~~~~~~~~~~~~~~~~~
devdescr.cc:2251:2: warning: address of array 'atmega32m1_io_registers' will always evaluate to 'true' [-Wpointer-bool-conversion]
        atmega32m1_io_registers,
        ^~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
~~~
The problem appears to be two instances of static initialzation of the wrong field.  These look like straight up bugs to me that the newer compiler with better warning detects.

This issue was migrated from https://sourceforge.net/p/avarice/bugs/28/

**Comment by avrs-admin** [comment]
joerg_wunsch
2020-08-29 20:55:16.946000

Actually, this bug has been fixed long ago in the tree, as part of merging the EDBG changes.
So seems it's really high time to finally roll a new release, even though I'm not fully happy wit hthe stability of EDBG.

**Comment by avrs-admin** [comment]
joerg_wunsch
2020-08-29 20:56:11.633000

- **status**: open --> closed
- **assigned_to**: Joerg Wunsch
